services:
  user-service:
    container_name: user-service
    image: chokyuseong/user-service:latest
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ${USERNAME}
        SECRET_KEY: ${SECRET_KEY}
    ports:
      - '19092:19092'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    mem_limit: 1024mb
    cpus: 0.5
    networks:
      - limited-team25

networks:
  limited-team25:
    external: true